# Generated by Django 6.0.3 on 2026-03-27 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration_paper_pic', models.ImageField(default='car_registration_paper_pic/default.png', upload_to='car_registration_paper_pic/')),
                ('car_pic', models.ImageField(default='car_pic/default.png', upload_to='car_pic/')),
                ('car_maker', models.CharField(help_text='Example: Toyota', max_length=50)),
                ('car_model', models.CharField(help_text='Example: Toyota', max_length=50)),
                ('car_model_year', models.PositiveIntegerField(help_text='Example: 2022')),
                ('car_seat_capacity', models.PositiveBigIntegerField(default=4, help_text='Example: 5')),
                ('car_color', models.CharField(max_length=20)),
                ('car_plate_number', models.CharField(help_text='Example: Y36565', max_length=20, unique=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='drivers.driverprofile')),
            ],
        ),
    ]
